// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9RLFidBmpD8yMBCNj8UCRC4WjV3xJ2bI',
    appId: '1:472378030581:web:06452ffe50f2adf675c8bc',
    messagingSenderId: '472378030581',
    projectId: 'nurse-master',
    authDomain: 'nurse-master.firebaseapp.com',
    storageBucket: 'nurse-master.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCymd2CQ84FpoVOYUSWHfD0M4BFtd5wsA8',
    appId: '1:472378030581:android:0dfe0b4e838f844a75c8bc',
    messagingSenderId: '472378030581',
    projectId: 'nurse-master',
    storageBucket: 'nurse-master.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMddd1125538JbIN3rhHj-UZpECFbSQBc',
    appId: '1:472378030581:ios:e867685c5b8be5d975c8bc',
    messagingSenderId: '472378030581',
    projectId: 'nurse-master',
    storageBucket: 'nurse-master.appspot.com',
    androidClientId: '472378030581-mgutfhljlh2kc8sgu9fqlmud4nirhvp2.apps.googleusercontent.com',
    iosClientId: '472378030581-s56sj4mv1204cr21u6cmkitmgfb355io.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalNursing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMddd1125538JbIN3rhHj-UZpECFbSQBc',
    appId: '1:472378030581:ios:e867685c5b8be5d975c8bc',
    messagingSenderId: '472378030581',
    projectId: 'nurse-master',
    storageBucket: 'nurse-master.appspot.com',
    androidClientId: '472378030581-mgutfhljlh2kc8sgu9fqlmud4nirhvp2.apps.googleusercontent.com',
    iosClientId: '472378030581-s56sj4mv1204cr21u6cmkitmgfb355io.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalNursing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9RLFidBmpD8yMBCNj8UCRC4WjV3xJ2bI',
    appId: '1:472378030581:web:741dc806f5578a9575c8bc',
    messagingSenderId: '472378030581',
    projectId: 'nurse-master',
    authDomain: 'nurse-master.firebaseapp.com',
    storageBucket: 'nurse-master.appspot.com',
  );

}